<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Canton;

class CantonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Canton::create([ 'id' => 0, 'name' => 'NO ESPECIFICADO', 'province_id' => '0']);
        Canton::create([ 'id' => 1, 'name' => 'PORTOVIEJO', 'province_id' => '13']);
        Canton::create([ 'id' => 2, 'name' => 'MANTA', 'province_id' => '13']);
        Canton::create([ 'id' => 3, 'name' => 'SUCRE', 'province_id' => '13']);
        Canton::create([ 'id' => 4, 'name' => 'CHONE', 'province_id' => '13']);
        Canton::create([ 'id' => 5, 'name' => 'BOLIVAR', 'province_id' => '13']);
        Canton::create([ 'id' => 6, 'name' => '24 DE MAYO', 'province_id' => '13']);
        Canton::create([ 'id' => 7, 'name' => 'EL CARMEN', 'province_id' => '13']);
        Canton::create([ 'id' => 8, 'name' => 'JIPIJAPA', 'province_id' => '13']);
        Canton::create([ 'id' => 9, 'name' => 'MONTECRISTI', 'province_id' => '13']);
        Canton::create([ 'id' => 10, 'name' => 'PAJAN', 'province_id' => '13']);
        Canton::create([ 'id' => 11, 'name' => 'PEDERNALES', 'province_id' => '13']);
        Canton::create([ 'id' => 12, 'name' => 'PUERTO LOPEZ', 'province_id' => '13']);
        Canton::create([ 'id' => 13, 'name' => 'ROCAFUERTE', 'province_id' => '13']);
        Canton::create([ 'id' => 14, 'name' => 'OLMEDO', 'province_id' => '13']);
        Canton::create([ 'id' => 16, 'name' => 'JARAMIJO', 'province_id' => '13']);
        Canton::create([ 'id' => 17, 'name' => 'TOSAGUA', 'province_id' => '13']);
        Canton::create([ 'id' => 18, 'name' => 'JUNIN', 'province_id' => '13']);
        Canton::create([ 'id' => 19, 'name' => 'JAMA', 'province_id' => '13']);
        Canton::create([ 'id' => 20, 'name' => 'PICHINCHA', 'province_id' => '13']);
        Canton::create([ 'id' => 21, 'name' => 'FLAVIO ALFARO', 'province_id' => '13']);
        Canton::create([ 'id' => 36, 'name' => 'GUAYAQUIL', 'province_id' => '9']);
        Canton::create([ 'id' => 37, 'name' => 'QUEVEDO', 'province_id' => '12']);
        Canton::create([ 'id' => 38, 'name' => 'ESMERALDAS', 'province_id' => '8']);
        Canton::create([ 'id' => 39, 'name' => 'SANTA ANA', 'province_id' => '13']);
        Canton::create([ 'id' => 40, 'name' => 'DAULE', 'province_id' => '9']);
        Canton::create([ 'id' => 43, 'name' => 'SALINAS', 'province_id' => '24']);
        Canton::create([ 'id' => 44, 'name' => 'VENEZUELA', 'province_id' => '26']);
        Canton::create([ 'id' => 45, 'name' => 'LA LIBERTAD', 'province_id' => '24']);
        Canton::create([ 'id' => 46, 'name' => 'LOJA', 'province_id' => '11']);
        Canton::create([ 'id' => 47, 'name' => 'SANTA CRUZ', 'province_id' => '20']);
        Canton::create([ 'id' => 48, 'name' => 'QUITO', 'province_id' => '17']);
        Canton::create([ 'id' => 49, 'name' => 'EL TRIUNFO', 'province_id' => '9']);
        Canton::create([ 'id' => 50, 'name' => 'CEVALLOS', 'province_id' => '18']);
        Canton::create([ 'id' => 51, 'name' => 'PASAJE', 'province_id' => '7']);
        Canton::create([ 'id' => 52, 'name' => 'IBARRA', 'province_id' => '10']);
        Canton::create([ 'id' => 53, 'name' => 'RIOBAMBA', 'province_id' => '6']);
        Canton::create([ 'id' => 54, 'name' => 'SANTO DOMINGO', 'province_id' => '23']);
        Canton::create([ 'id' => 55, 'name' => 'EL EMPALME', 'province_id' => '9']);
        Canton::create([ 'id' => 56, 'name' => 'CARACAS', 'province_id' => '26']);
        Canton::create([ 'id' => 57, 'name' => 'PATATE', 'province_id' => '18']);
        Canton::create([ 'id' => 61, 'name' => 'MEXICO', 'province_id' => '29']);
        Canton::create([ 'id' => 62, 'name' => 'CUENCA', 'province_id' => '1']);
        Canton::create([ 'id' => 63, 'name' => 'PELILEO', 'province_id' => '18']);
        Canton::create([ 'id' => 64, 'name' => 'SANTA ROSA', 'province_id' => '7']);
        Canton::create([ 'id' => 67, 'name' => 'ANTONIO ANTE', 'province_id' => '10']);
        Canton::create([ 'id' => 68, 'name' => 'BABAHOYO', 'province_id' => '12']);
        Canton::create([ 'id' => 69, 'name' => 'AZOGUES', 'province_id' => '3']);
        Canton::create([ 'id' => 70, 'name' => 'ZAMORA', 'province_id' => '19']);
        Canton::create([ 'id' => 71, 'name' => 'PUJILI', 'province_id' => '5']);
        Canton::create([ 'id' => 72, 'name' => 'LATACUNGA', 'province_id' => '5']);
        Canton::create([ 'id' => 73, 'name' => 'COLTA', 'province_id' => '6']);
        Canton::create([ 'id' => 74, 'name' => 'FONSECA', 'province_id' => '30']);
        Canton::create([ 'id' => 75, 'name' => 'BALZAR', 'province_id' => '9']);
        Canton::create([ 'id' => 76, 'name' => 'PLAYAS', 'province_id' => '9']);
        Canton::create([ 'id' => 77, 'name' => 'BRONX', 'province_id' => '31']);
        Canton::create([ 'id' => 78, 'name' => 'PEDRO CARBO', 'province_id' => '9']);
        Canton::create([ 'id' => 79, 'name' => 'MACHALA', 'province_id' => '7']);
        Canton::create([ 'id' => 80, 'name' => 'CARCHI', 'province_id' => '0']);
        Canton::create([ 'id' => 81, 'name' => 'NEW YORK', 'province_id' => '31']);
        Canton::create([ 'id' => 82, 'name' => 'BOLIVIA', 'province_id' => '69']);
        Canton::create([ 'id' => 83, 'name' => 'BOLIVAR', 'province_id' => '4']);
        Canton::create([ 'id' => 84, 'name' => 'SALCEDO', 'province_id' => '5']);
        Canton::create([ 'id' => 85, 'name' => 'HUAQUILLAS', 'province_id' => '7']);
        Canton::create([ 'id' => 86, 'name' => 'RIOCHACHA', 'province_id' => '30']);
        Canton::create([ 'id' => 87, 'name' => 'TUMACO', 'province_id' => '33']);
        Canton::create([ 'id' => 88, 'name' => 'CARTAGO', 'province_id' => '34']);
        Canton::create([ 'id' => 89, 'name' => 'TULUA', 'province_id' => '34']);
        Canton::create([ 'id' => 90, 'name' => 'CHICLAYO', 'province_id' => '0']);
        Canton::create([ 'id' => 91, 'name' => 'QUININDE', 'province_id' => '8']);
        Canton::create([ 'id' => 93, 'name' => 'TENA', 'province_id' => '15']);
        Canton::create([ 'id' => 94, 'name' => 'MADRID', 'province_id' => '37']);
        Canton::create([ 'id' => 95, 'name' => 'ESPAÑA', 'province_id' => '38']);
        Canton::create([ 'id' => 96, 'name' => 'ORELLANA', 'province_id' => '22']);
        Canton::create([ 'id' => 100, 'name' => 'LA MANA', 'province_id' => '5']);
        Canton::create([ 'id' => 101, 'name' => 'VILLAMIL', 'province_id' => '0']);
        Canton::create([ 'id' => 104, 'name' => 'MUISNE', 'province_id' => '8']);
        Canton::create([ 'id' => 105, 'name' => 'AMBATO', 'province_id' => '18']);
        Canton::create([ 'id' => 106, 'name' => 'PUERTO VILLAMIL', 'province_id' => '0']);
        Canton::create([ 'id' => 109, 'name' => 'SAN VICENTE', 'province_id' => '13']);
        Canton::create([ 'id' => 110, 'name' => 'BUENAVENTURA', 'province_id' => '34']);
        Canton::create([ 'id' => 112, 'name' => 'SANTA ELENA', 'province_id' => '24']);
        Canton::create([ 'id' => 113, 'name' => 'SHUSHUFINDI', 'province_id' => '21']);
        Canton::create([ 'id' => 114, 'name' => 'ALAUSI', 'province_id' => '6']);
        Canton::create([ 'id' => 115, 'name' => 'ALFREDO BAQUERIZO MORENO (JUJAN)', 'province_id' => '9']);
        Canton::create([ 'id' => 116, 'name' => 'ARAJUNO', 'province_id' => '16']);
        Canton::create([ 'id' => 117, 'name' => 'ARCHIDONA', 'province_id' => '15']);
        Canton::create([ 'id' => 118, 'name' => 'ARENILLAS', 'province_id' => '7']);
        Canton::create([ 'id' => 119, 'name' => 'ARGENTINA', 'province_id' => '39']);
        Canton::create([ 'id' => 120, 'name' => 'ATACAMES', 'province_id' => '8']);
        Canton::create([ 'id' => 121, 'name' => 'ATAHUALPA', 'province_id' => '7']);
        Canton::create([ 'id' => 122, 'name' => 'BABA', 'province_id' => '12']);
        Canton::create([ 'id' => 123, 'name' => 'BALAO', 'province_id' => '9']);
        Canton::create([ 'id' => 124, 'name' => 'BALSAS', 'province_id' => '7']);
        Canton::create([ 'id' => 125, 'name' => 'BIBLIAN', 'province_id' => '3']);
        Canton::create([ 'id' => 126, 'name' => 'BUENA FE', 'province_id' => '12']);
        Canton::create([ 'id' => 127, 'name' => 'CALUMA', 'province_id' => '2']);
        Canton::create([ 'id' => 128, 'name' => 'CALVAS', 'province_id' => '11']);
        Canton::create([ 'id' => 129, 'name' => 'AGUARICO', 'province_id' => '22']);
        Canton::create([ 'id' => 130, 'name' => 'LA JOYA DE LOS SACHAS', 'province_id' => '22']);
        Canton::create([ 'id' => 131, 'name' => 'LORETO', 'province_id' => '22']);
        Canton::create([ 'id' => 132, 'name' => 'CAÑAR', 'province_id' => '3']);
        Canton::create([ 'id' => 133, 'name' => 'CARLOS JULIO AROSEMENA TOLA', 'province_id' => '15']);
        Canton::create([ 'id' => 134, 'name' => 'CASCALES', 'province_id' => '21']);
        Canton::create([ 'id' => 135, 'name' => 'CATAMAYO', 'province_id' => '11']);
        Canton::create([ 'id' => 136, 'name' => 'CAYAMBE', 'province_id' => '17']);
        Canton::create([ 'id' => 137, 'name' => 'CELICA', 'province_id' => '11']);
        Canton::create([ 'id' => 138, 'name' => 'CENTINELA DEL CONDOR', 'province_id' => '19']);
        Canton::create([ 'id' => 139, 'name' => 'CHAGUARPAMBA', 'province_id' => '11']);
        Canton::create([ 'id' => 140, 'name' => 'CHAMBO', 'province_id' => '6']);
        Canton::create([ 'id' => 141, 'name' => 'CHILE', 'province_id' => '40']);
        Canton::create([ 'id' => 142, 'name' => 'CHILLA', 'province_id' => '7']);
        Canton::create([ 'id' => 143, 'name' => 'CHILLANES', 'province_id' => '2']);
        Canton::create([ 'id' => 144, 'name' => 'CHIMBO', 'province_id' => '2']);
        Canton::create([ 'id' => 145, 'name' => 'CHINCHIPE', 'province_id' => '19']);
        Canton::create([ 'id' => 146, 'name' => 'CHORDELEG', 'province_id' => '1']);
        Canton::create([ 'id' => 147, 'name' => 'CHUNCHI', 'province_id' => '6']);
        Canton::create([ 'id' => 148, 'name' => 'COLIMES', 'province_id' => '9']);
        Canton::create([ 'id' => 149, 'name' => 'COLOMBIA', 'province_id' => '41']);
        Canton::create([ 'id' => 150, 'name' => 'CORONEL MARCELINO MARIDUEÑA', 'province_id' => '9']);
        Canton::create([ 'id' => 151, 'name' => 'COTACACHI', 'province_id' => '10']);
        Canton::create([ 'id' => 152, 'name' => 'CUMANDA', 'province_id' => '6']);
        Canton::create([ 'id' => 153, 'name' => 'CUYABENO', 'province_id' => '21']);
        Canton::create([ 'id' => 154, 'name' => 'DELEG', 'province_id' => '3']);
        Canton::create([ 'id' => 155, 'name' => 'DURAN', 'province_id' => '9']);
        Canton::create([ 'id' => 156, 'name' => 'ECHEANDIA', 'province_id' => '2']);
        Canton::create([ 'id' => 157, 'name' => 'EL CHACO', 'province_id' => '15']);
        Canton::create([ 'id' => 158, 'name' => 'EL GUABO', 'province_id' => '7']);
        Canton::create([ 'id' => 159, 'name' => 'EL PAN', 'province_id' => '1']);
        Canton::create([ 'id' => 160, 'name' => 'EL PANGUI', 'province_id' => '19']);
        Canton::create([ 'id' => 161, 'name' => 'EL PIEDRERO', 'province_id' => '90']);
        Canton::create([ 'id' => 162, 'name' => 'EL TAMBO', 'province_id' => '3']);
        Canton::create([ 'id' => 163, 'name' => 'ELOY ALFARO', 'province_id' => '8']);
        Canton::create([ 'id' => 164, 'name' => 'EMPALME', 'province_id' => '0']);
        Canton::create([ 'id' => 165, 'name' => 'ESPEJO', 'province_id' => '4']);
        Canton::create([ 'id' => 166, 'name' => 'ESPINDOLA', 'province_id' => '11']);
        Canton::create([ 'id' => 167, 'name' => 'GENERAL ANTONIO ELIZALDE', 'province_id' => '9']);
        Canton::create([ 'id' => 168, 'name' => 'GIRON', 'province_id' => '1']);
        Canton::create([ 'id' => 169, 'name' => 'GONZALO PIZARRO', 'province_id' => '21']);
        Canton::create([ 'id' => 170, 'name' => 'GONZANAMA', 'province_id' => '11']);
        Canton::create([ 'id' => 171, 'name' => 'GUACHAPALA', 'province_id' => '1']);
        Canton::create([ 'id' => 172, 'name' => 'GUALACEO', 'province_id' => '1']);
        Canton::create([ 'id' => 173, 'name' => 'GUALAQUIZA', 'province_id' => '14']);
        Canton::create([ 'id' => 174, 'name' => 'GUAMOTE', 'province_id' => '6']);
        Canton::create([ 'id' => 175, 'name' => 'GUANO', 'province_id' => '6']);
        Canton::create([ 'id' => 176, 'name' => 'GUARANDA', 'province_id' => '2']);
        Canton::create([ 'id' => 177, 'name' => 'HUAMBOYA', 'province_id' => '14']);
        Canton::create([ 'id' => 178, 'name' => 'IRAN', 'province_id' => '42']);
        Canton::create([ 'id' => 179, 'name' => 'ISABELA', 'province_id' => '20']);
        Canton::create([ 'id' => 180, 'name' => 'ISIDRO AYORA', 'province_id' => '9']);
        Canton::create([ 'id' => 181, 'name' => 'LA CONCORDIA', 'province_id' => '8']);
        Canton::create([ 'id' => 182, 'name' => 'LA TRONCAL', 'province_id' => '3']);
        Canton::create([ 'id' => 183, 'name' => 'LAGO AGRIO', 'province_id' => '21']);
        Canton::create([ 'id' => 184, 'name' => 'LAS GOLONDRINAS', 'province_id' => '90']);
        Canton::create([ 'id' => 185, 'name' => 'LAS LAJAS', 'province_id' => '7']);
        Canton::create([ 'id' => 186, 'name' => 'LAS NAVES', 'province_id' => '2']);
        Canton::create([ 'id' => 187, 'name' => 'LIMON INDANZA', 'province_id' => '14']);
        Canton::create([ 'id' => 188, 'name' => 'LOGROÑO', 'province_id' => '14']);
        Canton::create([ 'id' => 189, 'name' => 'LOMAS DE SARGENTILLO', 'province_id' => '9']);
        Canton::create([ 'id' => 191, 'name' => 'MACARA', 'province_id' => '11']);
        Canton::create([ 'id' => 192, 'name' => 'MANGA DEL CURA', 'province_id' => '90']);
        Canton::create([ 'id' => 193, 'name' => 'MARCABELI', 'province_id' => '7']);
        Canton::create([ 'id' => 194, 'name' => 'MERA', 'province_id' => '16']);
        Canton::create([ 'id' => 195, 'name' => 'MILAGRO', 'province_id' => '9']);
        Canton::create([ 'id' => 196, 'name' => 'MIRA', 'province_id' => '4']);
        Canton::create([ 'id' => 197, 'name' => 'MOCACHE', 'province_id' => '12']);
        Canton::create([ 'id' => 198, 'name' => 'MOCHA', 'province_id' => '18']);
        Canton::create([ 'id' => 199, 'name' => 'MONTALVO', 'province_id' => '12']);
        Canton::create([ 'id' => 200, 'name' => 'MONTUFAR', 'province_id' => '4']);
        Canton::create([ 'id' => 201, 'name' => 'MORONA', 'province_id' => '14']);
        Canton::create([ 'id' => 202, 'name' => 'NABON', 'province_id' => '1']);
        Canton::create([ 'id' => 203, 'name' => 'NANGARITZA', 'province_id' => '19']);
        Canton::create([ 'id' => 204, 'name' => 'NARANJAL', 'province_id' => '9']);
        Canton::create([ 'id' => 205, 'name' => 'NARANJITO', 'province_id' => '9']);
        Canton::create([ 'id' => 206, 'name' => 'NOBOL', 'province_id' => '9']);
        Canton::create([ 'id' => 207, 'name' => 'OÑA', 'province_id' => '1']);
        Canton::create([ 'id' => 208, 'name' => 'OTAVALO', 'province_id' => '10']);
        Canton::create([ 'id' => 209, 'name' => 'PALANDA', 'province_id' => '19']);
        Canton::create([ 'id' => 210, 'name' => 'PALENQUE', 'province_id' => '12']);
        Canton::create([ 'id' => 211, 'name' => 'PALESTINA', 'province_id' => '9']);
        Canton::create([ 'id' => 212, 'name' => 'PALLATANGA', 'province_id' => '6']);
        Canton::create([ 'id' => 213, 'name' => 'PALORA', 'province_id' => '14']);
        Canton::create([ 'id' => 214, 'name' => 'PALTAS', 'province_id' => '11']);
        Canton::create([ 'id' => 215, 'name' => 'PANGUA', 'province_id' => '5']);
        Canton::create([ 'id' => 216, 'name' => 'PASTAZA', 'province_id' => '16']);
        Canton::create([ 'id' => 217, 'name' => 'PAUTE', 'province_id' => '1']);
        Canton::create([ 'id' => 218, 'name' => 'PEDRO MONCAYO', 'province_id' => '17']);
        Canton::create([ 'id' => 219, 'name' => 'PEDRO VICENTE MALDONADO', 'province_id' => '17']);
        Canton::create([ 'id' => 220, 'name' => 'PENIPE', 'province_id' => '6']);
        Canton::create([ 'id' => 221, 'name' => 'PERU', 'province_id' => '43']);
        Canton::create([ 'id' => 222, 'name' => 'PIMAMPIRO', 'province_id' => '10']);
        Canton::create([ 'id' => 223, 'name' => 'PINDAL', 'province_id' => '11']);
        Canton::create([ 'id' => 224, 'name' => 'PIÑAS', 'province_id' => '7']);
        Canton::create([ 'id' => 225, 'name' => 'PORTOVELO', 'province_id' => '7']);
        Canton::create([ 'id' => 226, 'name' => 'PUCARA', 'province_id' => '1']);
        Canton::create([ 'id' => 227, 'name' => 'PUEBLOVIEJO', 'province_id' => '12']);
        Canton::create([ 'id' => 228, 'name' => 'PUERTO QUITO', 'province_id' => '17']);
        Canton::create([ 'id' => 229, 'name' => 'PUTUMAYO', 'province_id' => '21']);
        Canton::create([ 'id' => 230, 'name' => 'PUYANGO', 'province_id' => '11']);
        Canton::create([ 'id' => 231, 'name' => 'QUERO', 'province_id' => '18']);
        Canton::create([ 'id' => 232, 'name' => 'QUIJOS', 'province_id' => '15']);
        Canton::create([ 'id' => 233, 'name' => 'QUILANGA', 'province_id' => '11']);
        Canton::create([ 'id' => 234, 'name' => 'RIO VERDE', 'province_id' => '8']);
        Canton::create([ 'id' => 235, 'name' => 'RUMIÑAHUI', 'province_id' => '17']);
        Canton::create([ 'id' => 236, 'name' => 'SAMBORONDON', 'province_id' => '9']);
        Canton::create([ 'id' => 237, 'name' => 'SAN CRISTOBAL', 'province_id' => '20']);
        Canton::create([ 'id' => 238, 'name' => 'SAN FERNANDO', 'province_id' => '1']);
        Canton::create([ 'id' => 239, 'name' => 'SAN JACINTO DE YAGUACHI', 'province_id' => '9']);
        Canton::create([ 'id' => 240, 'name' => 'SAN JUAN BOSCO', 'province_id' => '14']);
        Canton::create([ 'id' => 241, 'name' => 'SAN LORENZO', 'province_id' => '8']);
        Canton::create([ 'id' => 242, 'name' => 'SAN MIGUEL', 'province_id' => '2']);
        Canton::create([ 'id' => 243, 'name' => 'SAN MIGUEL DE LOS BANCOS', 'province_id' => '17']);
        Canton::create([ 'id' => 244, 'name' => 'SAN MIGUEL DE URCUQUI', 'province_id' => '10']);
        Canton::create([ 'id' => 245, 'name' => 'SAN PEDRO DE HUACA', 'province_id' => '4']);
        Canton::create([ 'id' => 246, 'name' => 'SAN PEDRO DE PELILEO', 'province_id' => '18']);
        Canton::create([ 'id' => 247, 'name' => 'SANTA CLARA', 'province_id' => '16']);
        Canton::create([ 'id' => 248, 'name' => 'SANTA ISABEL', 'province_id' => '1']);
        Canton::create([ 'id' => 249, 'name' => 'SANTA LUCIA', 'province_id' => '9']);
        Canton::create([ 'id' => 250, 'name' => 'SANTIAGO', 'province_id' => '14']);
        Canton::create([ 'id' => 251, 'name' => 'SANTIAGO DE PILLARO', 'province_id' => '18']);
        Canton::create([ 'id' => 252, 'name' => 'SAQUISILI', 'province_id' => '5']);
        Canton::create([ 'id' => 253, 'name' => 'SARAGURO', 'province_id' => '11']);
        Canton::create([ 'id' => 254, 'name' => 'SEVILLA DE ORO', 'province_id' => '1']);
        Canton::create([ 'id' => 255, 'name' => 'SIGCHOS', 'province_id' => '5']);
        Canton::create([ 'id' => 256, 'name' => 'SIGSIG', 'province_id' => '1']);
        Canton::create([ 'id' => 257, 'name' => 'SIMON BOLIVAR', 'province_id' => '9']);
        Canton::create([ 'id' => 258, 'name' => 'SOZORANGA', 'province_id' => '11']);
        Canton::create([ 'id' => 259, 'name' => 'SUCUA', 'province_id' => '14']);
        Canton::create([ 'id' => 260, 'name' => 'SUCUMBIOS', 'province_id' => '21']);
        Canton::create([ 'id' => 261, 'name' => 'SUSCAL', 'province_id' => '3']);
        Canton::create([ 'id' => 262, 'name' => 'TAISHA', 'province_id' => '14']);
        Canton::create([ 'id' => 263, 'name' => 'TISALEO', 'province_id' => '18']);
        Canton::create([ 'id' => 264, 'name' => 'TULCAN', 'province_id' => '4']);
        Canton::create([ 'id' => 265, 'name' => 'URBINA JADO', 'province_id' => '0']);
        Canton::create([ 'id' => 266, 'name' => 'URDANETA', 'province_id' => '12']);
        Canton::create([ 'id' => 267, 'name' => 'VALENCIA', 'province_id' => '12']);
        Canton::create([ 'id' => 268, 'name' => 'VENTANAS', 'province_id' => '12']);
        Canton::create([ 'id' => 269, 'name' => 'VINCES', 'province_id' => '12']);
        Canton::create([ 'id' => 270, 'name' => 'YACUAMBI', 'province_id' => '19']);
        Canton::create([ 'id' => 271, 'name' => 'YANTZAZA (YANZATZA)', 'province_id' => '19']);
        Canton::create([ 'id' => 272, 'name' => 'ZAPOTILLO', 'province_id' => '11']);
        Canton::create([ 'id' => 273, 'name' => 'ZARUMA', 'province_id' => '7']);
        Canton::create([ 'id' => 274, 'name' => 'ECUADOR', 'province_id' => '0']);
        Canton::create([ 'id' => 275, 'name' => 'CHARAPOTO', 'province_id' => '0']);
        Canton::create([ 'id' => 276, 'name' => 'SANTA CRUZ', 'province_id' => '0']);
        Canton::create([ 'id' => 277, 'name' => 'PUERTO AYORA', 'province_id' => '0']);
        Canton::create([ 'id' => 278, 'name' => 'MARYLAND', 'province_id' => '47']);
        Canton::create([ 'id' => 280, 'name' => 'CUETIAL', 'province_id' => '33']);
        Canton::create([ 'id' => 281, 'name' => 'FAWN GROVE', 'province_id' => '49']);
        Canton::create([ 'id' => 282, 'name' => 'NO ESPECIFICADO', 'province_id' => '0']);
        Canton::create([ 'id' => 290, 'name' => 'SAN BLAS', 'province_id' => '0']);
        Canton::create([ 'id' => 291, 'name' => 'NEW JERSEY', 'province_id' => '55']);
        Canton::create([ 'id' => 296, 'name' => 'GONAIVE', 'province_id' => '57']);
        Canton::create([ 'id' => 297, 'name' => 'NUEVA LOJA', 'province_id' => '0']);
        Canton::create([ 'id' => 298, 'name' => 'QUINIDE', 'province_id' => '0']);
        Canton::create([ 'id' => 299, 'name' => 'BUENOS AIRES', 'province_id' => '0']);
        Canton::create([ 'id' => 300, 'name' => 'QUINDIO', 'province_id' => '61']);
        Canton::create([ 'id' => 301, 'name' => 'BOGOTA', 'province_id' => '0']);
        Canton::create([ 'id' => 302, 'name' => 'PASTAZA', 'province_id' => '0']);
        Canton::create([ 'id' => 303, 'name' => 'PALMIRA', 'province_id' => '34']);
        //Canton::create([ 'id' => 304, 'name' => 'JUJAN', 'province_id' => '0']);
        Canton::create([ 'id' => 305, 'name' => 'ITALIA', 'province_id' => '63']);
        //Canton::create([ 'id' => 309, 'name' => 'ABDON CALDERON', 'province_id' => '0']);
        //Canton::create([ 'id' => 311, 'name' => 'RIOCHICO', 'province_id' => '0']);
        //Canton::create([ 'id' => 312, 'name' => 'SOSOTE', 'province_id' => '0']);
        //Canton::create([ 'id' => 313, 'name' => 'PICOAZA', 'province_id' => '0']);
        //Canton::create([ 'id' => 314, 'name' => 'CALDERON', 'province_id' => '0']);
        //Canton::create([ 'id' => 315, 'name' => 'SUCRE', 'province_id' => '0']);
        //Canton::create([ 'id' => 316, 'name' => 'LA QUEBRADITA', 'province_id' => '0']);
        Canton::create([ 'id' => 318, 'name' => 'QUINSALOMA', 'province_id' => '12']);
        Canton::create([ 'id' => 319, 'name' => 'CAMILO PONCE ENRIQUEZ', 'province_id' => '1']);
        Canton::create([ 'id' => 320, 'name' => 'AGUARICO', 'province_id' => '22']);
        Canton::create([ 'id' => 321, 'name' => 'SALITRE (URBINA JADO)', 'province_id' => '9']);
        Canton::create([ 'id' => 322, 'name' => 'BAÑOS DE AGUA SANTA', 'province_id' => '18']);
        Canton::create([ 'id' => 323, 'name' => 'LA JOYA DE LOS SACHAS', 'province_id' => '22']);
        Canton::create([ 'id' => 324, 'name' => 'LORETO', 'province_id' => '22']);
        Canton::create([ 'id' => 325, 'name' => 'MEJIA', 'province_id' => '17']);
        Canton::create([ 'id' => 326, 'name' => 'PABLO SEXTO', 'province_id' => '14']);
        Canton::create([ 'id' => 327, 'name' => 'PAQUISHA', 'province_id' => '19']);
        Canton::create([ 'id' => 328, 'name' => 'TIWINTZA', 'province_id' => '14']);
        Canton::create([ 'id' => 329, 'name' => 'OLMEDO', 'province_id' => '11']);
        Canton::create([ 'id' => 330, 'name' => 'HONDURAS', 'province_id' => '91']);
        Canton::create([ 'id' => 331, 'name' => 'BRASIL', 'province_id' => '92']);
        Canton::create([ 'id' => 332, 'name' => 'NICARAGUA', 'province_id' => '93']);
        Canton::create([ 'id' => 333, 'name' => 'CARTAGENA', 'province_id' => '94']);
        Canton::create([ 'id' => 334, 'name' => 'CUBA', 'province_id' => '95']);

    }
}
