<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create([ 'id' => 0, 'name' => 'NO ESPECIFICADO', 'code' => '']);
        Country::create([ 'id' => 1, 'name' => 'ECUADOR', 'code' => 'EC']);
        Country::create([ 'id' => 2, 'name' => 'VENEZUELA', 'code' => 'VE']);
        Country::create([ 'id' => 3, 'name' => 'COLOMBIA', 'code' => 'CO']);
        Country::create([ 'id' => 4, 'name' => 'PERU', 'code' => 'PE']);
        Country::create([ 'id' => 5, 'name' => 'BOLIVIA', 'code' => 'BO']);
        Country::create([ 'id' => 6, 'name' => 'CHILE', 'code' => 'CL']);
        Country::create([ 'id' => 7, 'name' => 'ARGENTINA', 'code' => 'AR']);
        Country::create([ 'id' => 8, 'name' => 'URUGUAY', 'code' => 'UY']);
        Country::create([ 'id' => 9, 'name' => 'PARAGUAY', 'code' => 'PY']);
        Country::create([ 'id' => 10, 'name' => 'BRASIL', 'code' => 'BR']);
        Country::create([ 'id' => 11, 'name' => 'PANAMA', 'code' => 'PA']);
        Country::create([ 'id' => 12, 'name' => 'COSTA RICA', 'code' => 'CR']);
        Country::create([ 'id' => 13, 'name' => 'NICARAGUA', 'code' => 'NI']);
        Country::create([ 'id' => 14, 'name' => 'HONDURAS', 'code' => 'HN']);
        Country::create([ 'id' => 15, 'name' => 'GUATEMALA', 'code' => 'GT']);
        Country::create([ 'id' => 16, 'name' => 'CUBA', 'code' => 'CU']);
        Country::create([ 'id' => 17, 'name' => 'REP. DOMINICANA', 'code' => 'DO']);
        Country::create([ 'id' => 18, 'name' => 'PUERTO RICO', 'code' => 'PR']);
        Country::create([ 'id' => 19, 'name' => 'JAMAICA', 'code' => 'JM']);
        Country::create([ 'id' => 21, 'name' => 'ESTADOS UNIDOS', 'code' => 'US']);
        Country::create([ 'id' => 22, 'name' => 'MEXICO', 'code' => 'MX']);
        Country::create([ 'id' => 23, 'name' => 'ESPAÑA', 'code' => 'ES']);
        Country::create([ 'id' => 24, 'name' => 'AFGANISTAN', 'code' => 'AF']);
        Country::create([ 'id' => 25, 'name' => 'ALBANIA', 'code' => 'AL']);
        Country::create([ 'id' => 26, 'name' => 'ALEMANIA', 'code' => 'DE']);
        Country::create([ 'id' => 27, 'name' => 'ANDORRA', 'code' => 'AD']);
        Country::create([ 'id' => 28, 'name' => 'ANGOLA', 'code' => 'AO']);
        Country::create([ 'id' => 29, 'name' => 'ANGUILLA', 'code' => 'AI']);
        Country::create([ 'id' => 30, 'name' => 'ANTIGUA Y BARBUDA', 'code' => 'AG']);
        Country::create([ 'id' => 31, 'name' => 'ANTILLAS HOLANDESA', 'code' => 'AN']);
        Country::create([ 'id' => 32, 'name' => 'ARABIA SAUDITA', 'code' => 'SA']);
        Country::create([ 'id' => 33, 'name' => 'ARGELIA', 'code' => 'DZ']);
        Country::create([ 'id' => 34, 'name' => 'ARMENIA', 'code' => 'AM']);
        Country::create([ 'id' => 35, 'name' => 'ARUBA', 'code' => 'AW']);
        Country::create([ 'id' => 36, 'name' => 'AUSTRALIA', 'code' => 'AU']);
        Country::create([ 'id' => 37, 'name' => 'AUSTRIA', 'code' => 'AT']);
        Country::create([ 'id' => 38, 'name' => 'AZERBAIYAN', 'code' => 'AZ']);
        Country::create([ 'id' => 39, 'name' => 'BAHAMAS', 'code' => 'BS']);
        Country::create([ 'id' => 40, 'name' => 'BAHREIN', 'code' => 'BH']);
        Country::create([ 'id' => 41, 'name' => 'BANGLADESH', 'code' => 'BD']);
        Country::create([ 'id' => 42, 'name' => 'BARBADOS', 'code' => 'BB']);
        Country::create([ 'id' => 43, 'name' => 'BELARUS', 'code' => 'BY']);
        Country::create([ 'id' => 44, 'name' => 'BELGICA', 'code' => 'BE']);
        Country::create([ 'id' => 45, 'name' => 'BELICE', 'code' => 'BJ']);
        Country::create([ 'id' => 46, 'name' => 'BENIN', 'code' => 'BJ']);
        Country::create([ 'id' => 47, 'name' => 'BERMUDAS', 'code' => 'BM']);
        Country::create([ 'id' => 48, 'name' => 'BHUTAN', 'code' => 'BT']);
        Country::create([ 'id' => 49, 'name' => 'BOSNIA Y HERZEGOVINA', 'code' => 'BA']);
        Country::create([ 'id' => 50, 'name' => 'BOTSWANIA', 'code' => 'BW']);
        Country::create([ 'id' => 51, 'name' => 'BRUNEI', 'code' => 'BN']);
        Country::create([ 'id' => 52, 'name' => 'BULGARIA', 'code' => 'BG']);
        Country::create([ 'id' => 53, 'name' => 'BURKINA FASO', 'code' => 'BF']);
        Country::create([ 'id' => 54, 'name' => 'BURUBDI', 'code' => 'BI']);
        Country::create([ 'id' => 55, 'name' => 'CABO VERDE', 'code' => 'CV']);
        Country::create([ 'id' => 56, 'name' => 'CAMBOYA', 'code' => 'KH']);
        Country::create([ 'id' => 57, 'name' => 'CAMERUN', 'code' => 'CM']);
        Country::create([ 'id' => 58, 'name' => 'CANADA', 'code' => 'CA']);
        Country::create([ 'id' => 59, 'name' => 'CHAD', 'code' => 'TD']);
        Country::create([ 'id' => 60, 'name' => 'COCOS ( KEELING) ISLANDS', 'code' => 'CC']);
        Country::create([ 'id' => 61, 'name' => 'COMORAS', 'code' => 'KM']);
        Country::create([ 'id' => 62, 'name' => 'CONGO', 'code' => 'CG']);
        Country::create([ 'id' => 63, 'name' => 'COREA (NORTE)', 'code' => 'KP']);
        Country::create([ 'id' => 64, 'name' => 'COREA (SUR)', 'code' => 'KR']);
        Country::create([ 'id' => 65, 'name' => 'COSTA DE MARFIL', 'code' => 'CI']);
        Country::create([ 'id' => 66, 'name' => 'CROACIA', 'code' => 'HR']);
        Country::create([ 'id' => 67, 'name' => 'DIJIBOUTI', 'code' => 'DJ']);
        Country::create([ 'id' => 68, 'name' => 'DINAMARCA', 'code' => 'DK']);
        Country::create([ 'id' => 69, 'name' => 'EGIPTO', 'code' => 'EG']);
        Country::create([ 'id' => 70, 'name' => 'EL SALVADOR', 'code' => 'SV']);
        Country::create([ 'id' => 71, 'name' => 'EMIRATOS ARABES UNIDOS', 'code' => 'AE']);
        Country::create([ 'id' => 72, 'name' => 'ERITREA', 'code' => 'ER']);
        Country::create([ 'id' => 73, 'name' => 'ESLOVENIA', 'code' => 'SI']);
        Country::create([ 'id' => 74, 'name' => 'ESTADO DE LA CIUDAD DEL VATICANO', 'code' => 'VA']);
        Country::create([ 'id' => 75, 'name' => 'ESTONIA', 'code' => 'EE']);
        Country::create([ 'id' => 76, 'name' => 'ETIOPIA', 'code' => 'ET']);
        Country::create([ 'id' => 77, 'name' => 'FEDERACION RUSA', 'code' => 'RU']);
        Country::create([ 'id' => 78, 'name' => 'FIJI', 'code' => 'FJ']);
        Country::create([ 'id' => 79, 'name' => 'FILIPINAS', 'code' => 'PH']);
        Country::create([ 'id' => 80, 'name' => 'FINLANDIA', 'code' => 'FI']);
        Country::create([ 'id' => 81, 'name' => 'FRANCIA', 'code' => 'FR']);
        Country::create([ 'id' => 82, 'name' => 'GABON', 'code' => 'GA']);
        Country::create([ 'id' => 83, 'name' => 'GAMBIA', 'code' => 'GM']);
        Country::create([ 'id' => 84, 'name' => 'GHANA', 'code' => 'GH']);
        Country::create([ 'id' => 85, 'name' => 'GIBRALTAR', 'code' => 'GI']);
        Country::create([ 'id' => 86, 'name' => 'GRAN BRETAÑA (UK)', 'code' => 'GB']);
        Country::create([ 'id' => 87, 'name' => 'GRANADA', 'code' => 'GD']);
        Country::create([ 'id' => 88, 'name' => 'GRECIA', 'code' => 'GR']);
        Country::create([ 'id' => 89, 'name' => 'GROENLANDIA', 'code' => 'GL']);
        Country::create([ 'id' => 90, 'name' => 'GUADALUPE', 'code' => 'GP']);
        Country::create([ 'id' => 91, 'name' => 'GUAM', 'code' => 'GU']);
        Country::create([ 'id' => 92, 'name' => 'GUINEA', 'code' => 'GN']);
        Country::create([ 'id' => 93, 'name' => 'GUINEA ECUATORIAL', 'code' => 'GQ']);
        Country::create([ 'id' => 94, 'name' => 'GUINEA-BISSAU', 'code' => 'GW']);
        Country::create([ 'id' => 95, 'name' => 'GUYANA', 'code' => 'GY']);
        Country::create([ 'id' => 96, 'name' => 'GUYANA FRANCESA', 'code' => 'GF']);
        Country::create([ 'id' => 97, 'name' => 'HAITI', 'code' => 'HT']);
        Country::create([ 'id' => 98, 'name' => 'HOLANDA', 'code' => 'NL']);
        Country::create([ 'id' => 99, 'name' => 'HONG KONG', 'code' => 'HK']);
        Country::create([ 'id' => 100, 'name' => 'HUNGRIA', 'code' => 'HU']);
        Country::create([ 'id' => 101, 'name' => 'INDIA', 'code' => 'IN']);
        Country::create([ 'id' => 102, 'name' => 'INDONESIA', 'code' => 'ID']);
        Country::create([ 'id' => 103, 'name' => 'IRAN', 'code' => 'IR']);
        Country::create([ 'id' => 104, 'name' => 'IRAQ', 'code' => 'IQ']);
        Country::create([ 'id' => 105, 'name' => 'IRLANDA', 'code' => 'IE']);
        Country::create([ 'id' => 106, 'name' => 'ISLANDIA', 'code' => 'IS']);
        Country::create([ 'id' => 107, 'name' => 'ISLAS CAIMAN', 'code' => 'KY']);
        Country::create([ 'id' => 108, 'name' => 'ISLAS COOK', 'code' => 'CK']);
        Country::create([ 'id' => 109, 'name' => 'ISLAS MALVINAS', 'code' => 'FK']);
        Country::create([ 'id' => 110, 'name' => 'ISLAS SALOMON', 'code' => 'SB']);
        Country::create([ 'id' => 111, 'name' => 'ISLAS VIRGENES (BRITANICAS)', 'code' => 'VG']);
        Country::create([ 'id' => 112, 'name' => 'ISLAS VIRGENES (U.S.)', 'code' => 'VI']);
        Country::create([ 'id' => 113, 'name' => 'ISRAEL', 'code' => 'IL']);
        Country::create([ 'id' => 114, 'name' => 'ITALIA', 'code' => 'IT']);
        Country::create([ 'id' => 115, 'name' => 'JAMAICA', 'code' => 'JM']);
        Country::create([ 'id' => 116, 'name' => 'JAPON', 'code' => 'JP']);
        Country::create([ 'id' => 117, 'name' => 'JORDAN', 'code' => 'JO']);
        Country::create([ 'id' => 118, 'name' => 'KAZAJSTAN', 'code' => 'KZ']);
        Country::create([ 'id' => 119, 'name' => 'KENIA', 'code' => 'KE']);
        Country::create([ 'id' => 120, 'name' => 'KIRGUISTAN', 'code' => 'KI']);
        Country::create([ 'id' => 121, 'name' => 'KUWAIT', 'code' => 'KW']);
        Country::create([ 'id' => 122, 'name' => 'LAOS', 'code' => 'LA']);
        Country::create([ 'id' => 123, 'name' => 'LATVIA', 'code' => 'LV']);
        Country::create([ 'id' => 124, 'name' => 'LESOTHO', 'code' => 'LS']);
        Country::create([ 'id' => 125, 'name' => 'LIBANO', 'code' => 'LB']);
        Country::create([ 'id' => 126, 'name' => 'LIBERIA', 'code' => 'LR']);
        Country::create([ 'id' => 127, 'name' => 'LIBIA', 'code' => 'LY']);
        Country::create([ 'id' => 128, 'name' => 'LIECHTENSTEIN', 'code' => 'LI']);
        Country::create([ 'id' => 129, 'name' => 'LITUANIA', 'code' => 'LT']);
        Country::create([ 'id' => 130, 'name' => 'LUXEMBURGO', 'code' => 'LU']);
        Country::create([ 'id' => 131, 'name' => 'MACAU', 'code' => 'MO']);
        Country::create([ 'id' => 132, 'name' => 'MACEDONIA', 'code' => 'MK']);
        Country::create([ 'id' => 133, 'name' => 'MADAGASCAR', 'code' => 'MG']);
        Country::create([ 'id' => 134, 'name' => 'MALASIA', 'code' => 'MY']);
        Country::create([ 'id' => 135, 'name' => 'MALAWI', 'code' => 'MW']);
        Country::create([ 'id' => 136, 'name' => 'MALDIVAS', 'code' => 'MV']);
        Country::create([ 'id' => 137, 'name' => 'MALI', 'code' => 'ML']);
        Country::create([ 'id' => 138, 'name' => 'MALTA', 'code' => 'MT']);
        Country::create([ 'id' => 139, 'name' => 'MARIANAS DEL NORTE ISLAS', 'code' => 'MP']);
        Country::create([ 'id' => 140, 'name' => 'MARRUECOS', 'code' => 'MA']);
        Country::create([ 'id' => 141, 'name' => 'MARSHALL ISLAS', 'code' => 'MH']);
        Country::create([ 'id' => 142, 'name' => 'MARTINICA', 'code' => 'MQ']);
        Country::create([ 'id' => 143, 'name' => 'MAURICIO', 'code' => 'MR']);
        Country::create([ 'id' => 144, 'name' => 'MICRONESIA', 'code' => 'FM']);
        Country::create([ 'id' => 145, 'name' => 'MOLDOVA', 'code' => 'MD']);
        Country::create([ 'id' => 146, 'name' => 'MONACO', 'code' => 'MC']);
        Country::create([ 'id' => 147, 'name' => 'MONGOLIA', 'code' => 'MN']);
        Country::create([ 'id' => 148, 'name' => 'MONTSERRAT', 'code' => 'MS']);
        Country::create([ 'id' => 149, 'name' => 'MOZAMBIQUE', 'code' => 'MZ']);
        Country::create([ 'id' => 150, 'name' => 'MYANMAR', 'code' => 'MM']);
        Country::create([ 'id' => 151, 'name' => 'NAMIBIA', 'code' => 'NA']);
        Country::create([ 'id' => 152, 'name' => 'NAURU', 'code' => 'NR']);
        Country::create([ 'id' => 153, 'name' => 'NEPAL', 'code' => 'NP']);
        Country::create([ 'id' => 154, 'name' => 'NICARAGUA 2', 'code' => 'NI']);
        Country::create([ 'id' => 155, 'name' => 'NIGER', 'code' => 'NE']);
        Country::create([ 'id' => 156, 'name' => 'NIGERIA', 'code' => 'NG']);
        Country::create([ 'id' => 157, 'name' => 'NIUE', 'code' => 'NU']);
        Country::create([ 'id' => 158, 'name' => 'NORFOLK ISLA', 'code' => 'NF']);
        Country::create([ 'id' => 159, 'name' => 'NORUEGA', 'code' => 'NO']);
        Country::create([ 'id' => 160, 'name' => 'NUEVA CALEDONIA', 'code' => 'NC']);
        Country::create([ 'id' => 161, 'name' => 'NUEVA ZELANDA', 'code' => 'NZ']);
        Country::create([ 'id' => 162, 'name' => 'OMAN', 'code' => 'OM']);
        Country::create([ 'id' => 163, 'name' => 'PAKISTAN', 'code' => 'PK']);
        Country::create([ 'id' => 164, 'name' => 'PALAU', 'code' => 'PW']);
        Country::create([ 'id' => 165, 'name' => 'PAPUA NUEVA GUINEA', 'code' => 'PG']);
        Country::create([ 'id' => 166, 'name' => 'PITACAIRN', 'code' => 'PN']);
        Country::create([ 'id' => 167, 'name' => 'POLINESIA FRANCESA', 'code' => 'PF']);
        Country::create([ 'id' => 168, 'name' => 'POLONIA', 'code' => 'PL']);
        Country::create([ 'id' => 169, 'name' => 'PORTUGAL', 'code' => 'PT']);
        Country::create([ 'id' => 170, 'name' => 'QATAR', 'code' => 'QA']);
        Country::create([ 'id' => 171, 'name' => 'REINO UNIDO', 'code' => 'UK']);
        Country::create([ 'id' => 172, 'name' => 'REPUBLICA CENTROAFRICANA', 'code' => 'CF']);
        Country::create([ 'id' => 173, 'name' => 'REPUBLICA CHECA', 'code' => 'CZ']);
        Country::create([ 'id' => 174, 'name' => 'REPUBLICA DE ESLOVAQUIA', 'code' => 'SK']);
        Country::create([ 'id' => 175, 'name' => 'REUNION', 'code' => 'RE']);
        Country::create([ 'id' => 176, 'name' => 'RUANDA', 'code' => 'RW']);
        Country::create([ 'id' => 177, 'name' => 'RUMANIA', 'code' => 'RO']);
        Country::create([ 'id' => 178, 'name' => 'SAHARA OCCIDENTAL', 'code' => 'EH']);
        Country::create([ 'id' => 179, 'name' => 'SAMOA', 'code' => 'AS']);
        Country::create([ 'id' => 180, 'name' => 'SAMOA OCCIDENTAL', 'code' => 'WS']);
        Country::create([ 'id' => 181, 'name' => 'SAN CRISTOBAL Y NIEVES', 'code' => 'KN']);
        Country::create([ 'id' => 182, 'name' => 'SAN MARINO', 'code' => 'SM']);
        Country::create([ 'id' => 183, 'name' => 'SAN PEDRO Y MIQUELON', 'code' => 'PM']);
        Country::create([ 'id' => 184, 'name' => 'SAN VICENTE Y LAS GRANADINAS', 'code' => 'VC']);
        Country::create([ 'id' => 185, 'name' => 'SANAT ELENA', 'code' => 'SH']);
        Country::create([ 'id' => 186, 'name' => 'SANTA LUCIA', 'code' => 'LC']);
        Country::create([ 'id' => 187, 'name' => 'SAO TOME AND PRINCIPE', 'code' => 'ST']);
        Country::create([ 'id' => 188, 'name' => 'SENEGAL', 'code' => 'SN']);
        Country::create([ 'id' => 189, 'name' => 'SEYCHELLES', 'code' => 'SC']);
        Country::create([ 'id' => 190, 'name' => 'SIERRE LEONE', 'code' => 'SL']);
        Country::create([ 'id' => 191, 'name' => 'SINGAPUR', 'code' => 'SG']);
        Country::create([ 'id' => 192, 'name' => 'SIRIA', 'code' => 'SY']);
        Country::create([ 'id' => 193, 'name' => 'SOMALIA', 'code' => 'SO']);
        Country::create([ 'id' => 194, 'name' => 'SRI LANKA', 'code' => 'LK']);
        Country::create([ 'id' => 195, 'name' => 'SUAZILANDIA', 'code' => 'SZ']);
        Country::create([ 'id' => 196, 'name' => 'SUDAFRICA', 'code' => 'ZA']);
        Country::create([ 'id' => 197, 'name' => 'SUDAN', 'code' => 'SD']);
        Country::create([ 'id' => 198, 'name' => 'SUECIA', 'code' => 'SE']);
        Country::create([ 'id' => 199, 'name' => 'SUIZA', 'code' => 'CH']);
        Country::create([ 'id' => 200, 'name' => 'SURINAME', 'code' => 'SR']);
        Country::create([ 'id' => 201, 'name' => 'TAILANDIA', 'code' => 'TH']);
        Country::create([ 'id' => 202, 'name' => 'TAIWAN', 'code' => 'TW']);
        Country::create([ 'id' => 203, 'name' => 'TANZANIA', 'code' => 'TZ']);
        Country::create([ 'id' => 204, 'name' => 'TAYIKISTAN', 'code' => 'TJ']);
        Country::create([ 'id' => 205, 'name' => 'TIERRAS AUSTRALES Y ANTARTICAS FRANCESAS', 'code' => 'TF']);
        Country::create([ 'id' => 206, 'name' => 'TIMOR ORIENTAL', 'code' => 'TP']);
        Country::create([ 'id' => 207, 'name' => 'TOGO', 'code' => 'TG']);
        Country::create([ 'id' => 208, 'name' => 'TOKELAU', 'code' => 'TK']);
        Country::create([ 'id' => 209, 'name' => 'TONGA', 'code' => 'TO']);
        Country::create([ 'id' => 210, 'name' => 'TRINIDAD Y TOBAGO', 'code' => 'TT']);
        Country::create([ 'id' => 211, 'name' => 'TUNEZ', 'code' => 'TN']);
        Country::create([ 'id' => 212, 'name' => 'TURCOS Y CAICOS, ISLAS', 'code' => 'TC']);
        Country::create([ 'id' => 213, 'name' => 'TURKMENISTAN', 'code' => 'TM']);
        Country::create([ 'id' => 214, 'name' => 'TURQUIA', 'code' => 'TR']);
        Country::create([ 'id' => 215, 'name' => 'TUVALU', 'code' => 'TV']);
        Country::create([ 'id' => 216, 'name' => 'UCRANIA', 'code' => 'UG']);
        Country::create([ 'id' => 217, 'name' => 'USSR', 'code' => 'SU']);
        Country::create([ 'id' => 218, 'name' => 'VANUATU', 'code' => 'VU']);
        Country::create([ 'id' => 219, 'name' => 'VIET NAM', 'code' => 'VN']);
        Country::create([ 'id' => 220, 'name' => 'YEMEN', 'code' => 'YE']);
        Country::create([ 'id' => 221, 'name' => 'YUGOSLAVIA', 'code' => 'YU']);
        Country::create([ 'id' => 222, 'name' => 'ZAIRE', 'code' => 'ZR']);
        Country::create([ 'id' => 223, 'name' => 'ZAMBIA', 'code' => 'ZM']);
        Country::create([ 'id' => 224, 'name' => 'ZIMBABWE', 'code' => 'ZW']);
        Country::create([ 'id' => 225, 'name' => 'ZONAS NO DELIMITADAS', 'code' => '']);
        Country::create([ 'id' => 226, 'name' => 'MONTENEGRO', 'code' => '']);
        Country::create([ 'id' => 227, 'name' => 'ESCOCIA', 'code' => '']);
        Country::create([ 'id' => 228, 'name' => 'RUSIA', 'code' => '']);
        Country::create([ 'id' => 229, 'name' => 'INGLATERRA', 'code' => '']);
        Country::create([ 'id' => 230, 'name' => 'CHINA', 'code' => '']);

    }
}
